/**
 * CrewAI Adapter
 *
 * Generates agents.yaml and tasks.yaml for CrewAI multi-agent systems.
 * Maps skills to agents and tasks with tool specifications.
 *
 * See: https://docs.crewai.com/
 */

import type { AgentStory } from '@/lib/schemas/story';
import type { Skill } from '@/lib/schemas/skill';
import { generateSlug } from '@/lib/schemas/skill';
import type {
  HarnessAdapter,
  HarnessCompatibility,
  HarnessOutput,
  HarnessFile,
  TryItConfig,
} from '../types';
import { registerAdapter } from '../registry';

// ============================================================================
// CrewAI Adapter Implementation
// ============================================================================

export const crewaiAdapter: HarnessAdapter = {
  id: 'crewai',
  name: 'CrewAI',
  description: 'Generate agents.yaml and tasks.yaml for CrewAI',
  icon: 'Users',
  url: 'https://crewai.com',

  canExport(story: AgentStory): HarnessCompatibility {
    const warnings: string[] = [];
    const missingFeatures: string[] = [];
    const unsupportedFeatures: string[] = [];

    // Basic validation
    if (!story.name) {
      missingFeatures.push('agent name');
    }

    if (!story.skills?.length) {
      warnings.push('Agent has no skills - will create a single general-purpose agent');
    }

    // CrewAI is designed for multi-agent, single agents work but may be overkill
    if (story.collaboration?.role !== 'supervisor') {
      warnings.push('CrewAI excels with supervisor agents coordinating workers');
    }

    // Check for schedule triggers (CrewAI has its own scheduling)
    const hasScheduleTriggers = story.skills?.some((skill) =>
      skill.triggers?.some((t) => t.type === 'schedule')
    );
    if (hasScheduleTriggers) {
      warnings.push('Schedule triggers should be configured in CrewAI task scheduling');
    }

    const compatible = missingFeatures.length === 0;

    return {
      compatible,
      warnings,
      missingFeatures,
      unsupportedFeatures,
    };
  },

  generate(story: AgentStory): HarnessOutput {
    const files: HarnessFile[] = [];
    const warnings: string[] = [];

    // Generate agents.yaml
    const agentsYaml = generateAgentsYaml(story);
    files.push({
      path: 'crewai/config/agents.yaml',
      content: agentsYaml,
    });

    // Generate tasks.yaml
    const tasksYaml = generateTasksYaml(story);
    files.push({
      path: 'crewai/config/tasks.yaml',
      content: tasksYaml,
    });

    // Generate main crew.py
    const crewPy = generateCrewPython(story);
    files.push({
      path: 'crewai/crew.py',
      content: crewPy,
    });

    // Generate tools.py if tools exist
    const toolsPy = generateToolsPython(story);
    if (toolsPy) {
      files.push({
        path: 'crewai/tools.py',
        content: toolsPy,
      });
    }

    // Generate requirements.txt
    files.push({
      path: 'crewai/requirements.txt',
      content: generateRequirements(),
    });

    const instructions = `
## Using with CrewAI

1. Install dependencies:
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`

2. Set your API key:
   \`\`\`bash
   export OPENAI_API_KEY=your-key
   # or for Anthropic
   export ANTHROPIC_API_KEY=your-key
   \`\`\`

3. Run the crew:
   \`\`\`bash
   python crew.py
   \`\`\`

4. Or import and customize:
   \`\`\`python
   from crew import ${generateSlug(story.name).replace(/-/g, '_')}Crew

   crew = ${generateSlug(story.name).replace(/-/g, '_')}Crew()
   result = crew.run()
   \`\`\`
`.trim();

    return { files, warnings, instructions };
  },

  getTryItConfig(story: AgentStory): TryItConfig | null {
    return {
      type: 'cli',
      command: `python crewai/crew.py`,
      setupInstructions: `
1. Install CrewAI: pip install crewai crewai-tools
2. Set ANTHROPIC_API_KEY or OPENAI_API_KEY environment variable
3. Run the command to start the crew
      `.trim(),
      description: 'Run CrewAI crew locally',
    };
  },
};

// ============================================================================
// Agents YAML Generation
// ============================================================================

function generateAgentsYaml(story: AgentStory): string {
  const lines: string[] = [
    `# CrewAI agents configuration for ${story.name}`,
    '# Generated by Agent Stories',
    '',
  ];

  // Main agent
  const mainAgentSlug = generateSlug(story.name);
  lines.push(`${mainAgentSlug}:`);
  lines.push(`  role: "${story.role || story.name}"`);
  lines.push(`  goal: "${story.purpose || `Assist users as ${story.name}`}"`);

  // Build backstory from role, purpose, and autonomy
  const backstoryParts: string[] = [];
  if (story.role) {
    backstoryParts.push(story.role);
  }
  if (story.autonomyLevel) {
    const autonomyDescriptions: Record<string, string> = {
      full: 'You operate with full autonomy to make independent decisions.',
      supervised: 'You handle routine tasks independently but escalate edge cases.',
      collaborative: 'You work collaboratively, proposing actions and seeking feedback.',
      directed: 'You follow explicit direction and request approval for actions.',
    };
    backstoryParts.push(autonomyDescriptions[story.autonomyLevel] || '');
  }
  lines.push(`  backstory: >`);
  for (const part of backstoryParts) {
    lines.push(`    ${part}`);
  }
  lines.push('');

  // Add skill-based agents if there are multiple skills
  if (story.skills && story.skills.length > 1) {
    for (const skill of story.skills) {
      const skillSlug = generateSlug(skill.name);
      lines.push(`${skillSlug}_specialist:`);
      lines.push(`  role: "${skill.name} Specialist"`);
      lines.push(`  goal: "${skill.description}"`);
      lines.push(`  backstory: >`);
      lines.push(`    You are a specialist in ${skill.name}.`);
      lines.push(`    ${skill.description}`);

      // Add success criteria as part of backstory
      if (skill.acceptance?.successConditions?.length) {
        lines.push(`    Success is measured by:`);
        for (const condition of skill.acceptance.successConditions) {
          lines.push(`    - ${condition}`);
        }
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ============================================================================
// Tasks YAML Generation
// ============================================================================

function generateTasksYaml(story: AgentStory): string {
  const lines: string[] = [
    `# CrewAI tasks configuration for ${story.name}`,
    '# Generated by Agent Stories',
    '',
  ];

  if (!story.skills?.length) {
    // Default task if no skills
    lines.push('main_task:');
    lines.push(`  description: "Perform the primary function of ${story.name}"`);
    lines.push(`  expected_output: "Task completed successfully"`);
    lines.push(`  agent: ${generateSlug(story.name)}`);
    return lines.join('\n');
  }

  const mainAgentSlug = generateSlug(story.name);

  for (const skill of story.skills) {
    const taskSlug = generateSlug(skill.name) + '_task';
    const agentSlug = story.skills.length > 1
      ? generateSlug(skill.name) + '_specialist'
      : mainAgentSlug;

    lines.push(`${taskSlug}:`);
    lines.push(`  description: >`);
    lines.push(`    ${skill.description}`);

    // Add behavior details
    if (skill.behavior) {
      switch (skill.behavior.model) {
        case 'sequential':
          lines.push('    ');
          lines.push('    Follow these steps:');
          skill.behavior.steps.forEach((step, i) => {
            lines.push(`    ${i + 1}. ${step}`);
          });
          break;
        case 'workflow':
          lines.push('    ');
          lines.push('    Process through these stages:');
          for (const stage of skill.behavior.stages) {
            lines.push(`    - ${stage.name}: ${stage.purpose}`);
          }
          break;
        case 'adaptive':
          lines.push('    ');
          lines.push('    Available approaches:');
          for (const cap of skill.behavior.capabilities) {
            lines.push(`    - ${cap}`);
          }
          break;
        case 'iterative':
          lines.push('    ');
          lines.push(`    Iterate until: ${skill.behavior.terminationCondition}`);
          break;
      }
    }

    // Expected output from acceptance criteria
    if (skill.acceptance?.successConditions?.length) {
      lines.push(`  expected_output: >`);
      lines.push(`    Success criteria met:`);
      for (const condition of skill.acceptance.successConditions) {
        lines.push(`    - ${condition}`);
      }
    } else {
      lines.push(`  expected_output: "Task completed successfully"`);
    }

    lines.push(`  agent: ${agentSlug}`);

    // Add tools if available
    if (skill.tools?.length) {
      lines.push(`  tools:`);
      for (const tool of skill.tools) {
        lines.push(`    - ${generateSlug(tool.name)}`);
      }
    }

    lines.push('');
  }

  return lines.join('\n');
}

// ============================================================================
// Crew Python Generation
// ============================================================================

function generateCrewPython(story: AgentStory): string {
  const className = generateSlug(story.name).replace(/-/g, '_').split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('') + 'Crew';

  const mainAgentSlug = generateSlug(story.name).replace(/-/g, '_');

  const lines: string[] = [
    '"""',
    `CrewAI crew: ${story.name}`,
    '',
    story.purpose || '',
    '"""',
    '',
    'from crewai import Agent, Crew, Task, Process',
    'from crewai.project import CrewBase, agent, crew, task',
    '',
  ];

  // Import tools if they exist
  const hasTools = story.skills?.some((s) => s.tools?.length);
  if (hasTools) {
    lines.push('from tools import get_tools');
  }

  lines.push('');
  lines.push('');
  lines.push('@CrewBase');
  lines.push(`class ${className}():`);
  lines.push(`    """${story.name} crew implementation."""`);
  lines.push('    ');
  lines.push('    agents_config = "config/agents.yaml"');
  lines.push('    tasks_config = "config/tasks.yaml"');
  lines.push('    ');

  // Agent definitions
  lines.push('    @agent');
  lines.push(`    def ${mainAgentSlug}(self) -> Agent:`);
  lines.push(`        """Create the main ${story.name} agent."""`);
  lines.push('        return Agent(');
  lines.push(`            config=self.agents_config["${generateSlug(story.name)}"],`);
  if (hasTools) {
    lines.push('            tools=get_tools(),');
  }
  lines.push('            verbose=True,');
  lines.push('        )');
  lines.push('    ');

  // Skill-based agents
  if (story.skills && story.skills.length > 1) {
    for (const skill of story.skills) {
      const skillSlug = generateSlug(skill.name).replace(/-/g, '_');
      lines.push('    @agent');
      lines.push(`    def ${skillSlug}_specialist(self) -> Agent:`);
      lines.push(`        """Create the ${skill.name} specialist agent."""`);
      lines.push('        return Agent(');
      lines.push(`            config=self.agents_config["${generateSlug(skill.name)}_specialist"],`);

      // Add skill-specific tools
      if (skill.tools?.length) {
        const toolNames = skill.tools.map((t) => generateSlug(t.name).replace(/-/g, '_'));
        lines.push(`            tools=[${toolNames.join(', ')}],`);
      }

      lines.push('            verbose=True,');
      lines.push('        )');
      lines.push('    ');
    }
  }

  // Task definitions
  if (story.skills?.length) {
    for (const skill of story.skills) {
      const taskSlug = generateSlug(skill.name).replace(/-/g, '_');
      const agentSlug = story.skills.length > 1
        ? taskSlug + '_specialist'
        : mainAgentSlug;

      lines.push('    @task');
      lines.push(`    def ${taskSlug}_task(self) -> Task:`);
      lines.push(`        """Create the ${skill.name} task."""`);
      lines.push('        return Task(');
      lines.push(`            config=self.tasks_config["${generateSlug(skill.name)}_task"],`);
      lines.push(`            agent=self.${agentSlug}(),`);
      lines.push('        )');
      lines.push('    ');
    }
  }

  // Crew definition
  lines.push('    @crew');
  lines.push('    def crew(self) -> Crew:');
  lines.push(`        """Create the ${story.name} crew."""`);
  lines.push('        return Crew(');
  lines.push('            agents=self.agents,');
  lines.push('            tasks=self.tasks,');

  // Set process based on collaboration role
  if (story.collaboration?.role === 'supervisor') {
    lines.push('            process=Process.hierarchical,');
    lines.push(`            manager_agent=self.${mainAgentSlug}(),`);
  } else {
    lines.push('            process=Process.sequential,');
  }

  lines.push('            verbose=True,');
  lines.push('        )');
  lines.push('');
  lines.push('');

  // Main entry point
  lines.push('def run():');
  lines.push(`    """Run the ${story.name} crew."""`);
  lines.push(`    crew = ${className}()`);
  lines.push('    result = crew.crew().kickoff()');
  lines.push('    print(result)');
  lines.push('    return result');
  lines.push('');
  lines.push('');
  lines.push('if __name__ == "__main__":');
  lines.push('    run()');

  return lines.join('\n');
}

// ============================================================================
// Tools Python Generation
// ============================================================================

function generateToolsPython(story: AgentStory): string | null {
  const allTools = story.skills?.flatMap((s) => s.tools || []) || [];
  if (!allTools.length) return null;

  const seenTools = new Set<string>();
  const lines: string[] = [
    '"""',
    `Tool definitions for ${story.name} CrewAI crew.`,
    '"""',
    '',
    'from crewai_tools import tool',
    '',
    '',
  ];

  for (const t of allTools) {
    const toolName = generateSlug(t.name).replace(/-/g, '_');
    if (seenTools.has(toolName)) continue;
    seenTools.add(toolName);

    lines.push('@tool');
    lines.push(`def ${toolName}() -> str:`);
    lines.push(`    """${t.purpose}""""`);
    lines.push(`    # TODO: Implement ${t.name}`);
    lines.push(`    return "Tool executed"`);
    lines.push('');
  }

  lines.push('');
  lines.push('def get_tools():');
  lines.push('    """Return all available tools."""');
  lines.push('    return [');
  const addedTools = new Set<string>();
  for (const t of allTools) {
    const toolName = generateSlug(t.name).replace(/-/g, '_');
    if (!addedTools.has(toolName)) {
      lines.push(`        ${toolName},`);
      addedTools.add(toolName);
    }
  }
  lines.push('    ]');

  return lines.join('\n');
}

// ============================================================================
// Requirements Generation
// ============================================================================

function generateRequirements(): string {
  return `crewai>=0.80.0
crewai-tools>=0.14.0
`;
}

// ============================================================================
// Register Adapter
// ============================================================================

registerAdapter(crewaiAdapter);
