/**
 * Harness Adapter Types
 *
 * Core interfaces for generating framework-specific configurations
 * from Agent Stories. Adapters translate agent definitions into
 * runtime-ready artifacts for various agent frameworks.
 */

import type { AgentStory } from '@/lib/schemas/story';

// ============================================================================
// Core Interfaces
// ============================================================================

/**
 * Compatibility assessment for an agent story with a specific harness.
 */
export interface HarnessCompatibility {
  /** Whether the story can be exported to this harness */
  compatible: boolean;
  /** Non-blocking warnings about potential issues */
  warnings: string[];
  /** Features in the story that this harness doesn't support */
  missingFeatures: string[];
  /** Harness features that can't be represented from this story */
  unsupportedFeatures: string[];
}

/**
 * A single file to be generated by an adapter.
 */
export interface HarnessFile {
  /** Relative path within the output (e.g., "claude/CLAUDE.md") */
  path: string;
  /** File content */
  content: string;
  /** Optional encoding (default: utf-8) */
  encoding?: 'utf-8' | 'base64';
}

/**
 * Output from a harness adapter's generate function.
 */
export interface HarnessOutput {
  /** Generated files */
  files: HarnessFile[];
  /** Human-readable instructions for using the output */
  instructions?: string;
  /** Warnings generated during export */
  warnings: string[];
}

/**
 * Configuration for the "Try It" launcher.
 */
export type TryItConfig =
  | TryItUrlConfig
  | TryItCliConfig
  | TryItApiConfig;

export interface TryItUrlConfig {
  type: 'url';
  /** URL to launch the harness with prefilled agent */
  launchUrl: string;
  /** Description of what happens when launched */
  description: string;
}

export interface TryItCliConfig {
  type: 'cli';
  /** CLI command to execute */
  command: string;
  /** Setup instructions */
  setupInstructions: string;
  /** Description of what the command does */
  description: string;
}

export interface TryItApiConfig {
  type: 'api';
  /** API endpoint */
  endpoint: string;
  /** HTTP method */
  method: 'GET' | 'POST' | 'PUT';
  /** Request payload */
  payload: Record<string, unknown>;
  /** Description of the API call */
  description: string;
}

// ============================================================================
// Adapter Interface
// ============================================================================

/**
 * A harness adapter transforms Agent Stories into framework-specific
 * configurations. Each adapter handles a single target framework.
 */
export interface HarnessAdapter {
  /** Unique identifier (e.g., "claude", "letta", "langgraph") */
  id: string;
  /** Display name for UI */
  name: string;
  /** Brief description of the harness */
  description: string;
  /** Lucide icon name for UI */
  icon: string;
  /** Website URL for the harness */
  url: string;

  /**
   * Check if a story is compatible with this harness.
   * Returns detailed compatibility information.
   */
  canExport(story: AgentStory): HarnessCompatibility;

  /**
   * Generate harness-specific configuration files.
   * Should only be called if canExport returns compatible: true.
   */
  generate(story: AgentStory): HarnessOutput;

  /**
   * Get configuration for the "Try It" launcher.
   * Returns null if this harness doesn't support direct launching.
   */
  getTryItConfig?(story: AgentStory): TryItConfig | null;
}

// ============================================================================
// Adapter Metadata
// ============================================================================

/**
 * Metadata for displaying adapters in the UI.
 */
export interface HarnessAdapterInfo {
  id: string;
  name: string;
  description: string;
  icon: string;
  url: string;
}

/**
 * Result of checking compatibility across all adapters.
 */
export type AdapterCompatibilityMap = Record<string, HarnessCompatibility>;

// ============================================================================
// Export Options
// ============================================================================

/**
 * Options for exporting to multiple harnesses.
 */
export interface HarnessExportOptions {
  /** Which adapters to use (default: all compatible) */
  adapterIds?: string[];
  /** Include source.json for round-trip editing */
  includeSource?: boolean;
}

/**
 * Result of a multi-harness export operation.
 */
export interface HarnessExportResult {
  /** Files organized by adapter ID */
  outputs: Record<string, HarnessOutput>;
  /** Combined warnings from all adapters */
  warnings: string[];
  /** The source.json if includeSource was true */
  source?: string;
}
